[package]
name = "rust_chainlink_ea_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "*"
serde_json = "*"
serde_derive = "*"
ethers = { git = "https://github.com/gakonst/ethers-rs" }
eyre = "0.6.8"
tokio = "1.20.1"
bytes = "0.4.12"
anyhow = {version = "1.0", features = ["std", "backtrace"] }
bao = "0.12.0"
blake3 = "1.3.1"
cid = "0.8.6"
sled = "0.34"
ctor = "0.1.23"
banyan-shared = { git = "https://github.com/banyancomputer/banyan-shared-rs" }
tempfile = "3.3.0"
dotenv = "0.15.0"
