[package]
name = "chainlink-proof-validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "*"
serde_json = "*"
anyhow = {version = "1.0", features = ["std", "backtrace"] }
banyan-shared ={git = "https://github.com/banyancomputer/banyan-shared-rs"}
dotenv = "0.15.0"
reqwest = "0.12.2"
log = "0.4.17"
tokio = "1.21.2"
rand = "0.8.5"
ethers = { git = "https://github.com/gakonst/ethers-rs" }