type = "directrequest"
schemaVersion = 1
name = "validate_ea_bridge_final"
externalJobID = "8a151377-9ab2-4089-b7d6-a52fb36dfb41"
maxTaskDuration = "0s"
contractAddress = "0xF1a252307Ff9F3fbB9598c9a181385122948b8Ae"
evmChainID = "5"
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type=cborparse data="$(decode_log.data)"]

    ds [type="bridge"
              name="rust_proof_verifier"
              requestData="{ \\"id\\": $(jobSpec.externalJobID),  \\"data\\": { \\"deal_id\\": $(decode_cbor.offer_id)}}"
              allowUnrestrictedNetworkAccess=true
              ]
parse        [type=jsonparse path="data" data="$(ds)"]
encode_data [type="ethabiencode" abi="(bytes32 requestId, uint256 offerID, uint256 successCount, uint256 numWindows, uint16 status, string result)" data="{ \\"requestId\\": $(decode_log.requestId), \\"offerID\\": $(parse.deal_id),  \\"successCount\\": $(parse.success_count),  \\"numWindows\\": $(parse.num_windows),  \\"status\\": $(parse.status),  \\"result\\": $(parse.result) }"]
encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\":   $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                  ]
submit_tx    [type="ethtx" to="0xF1a252307Ff9F3fbB9598c9a181385122948b8Ae" data="$(encode_tx)"]


decode_log -> decode_cbor -> ds -> parse -> encode_data -> encode_tx -> submit_tx
"""